version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yii2-app:latest
    container_name: yii2_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      YII_ENV: dev
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.25
    container_name: yii2_nginx
    restart: unless-stopped
    ports:
      - "8080:80"        
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: yii2_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
